name: Docker Healthcheck
on:
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 3 * * 1" # run every monday at 03:00 AM
jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker Compose
        run: docker compose build

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Check service health
        uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
        with:
          max-retries: 12
          retry-interval: 10
          compose-file: "docker-compose.yml"
          skip-exited: "false"  # unhealthy containers might exit and restart
          skip-no-healthcheck: "true"
